# Generated by Selenium IDE
from telnetlib import EC

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestreinicioclientes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()  # Pone el navegador en tamaño completo
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testreinicioclientes(self):
    self.driver.get('https://4er2v88hf6.execute-api.us-east-1.amazonaws.com/pwa-reset-test-deals')
    self.driver.maximize_window()
    time.sleep(5)
    # Seleccionar la opción deseada en el list box por su valor
    select = Select(self.driver.find_element(By.ID, "elementos"))
    select.select_by_index(17)

    self.driver.find_element(By.CSS_SELECTOR, ".radio-label:nth-child(3) span").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

    # Verificar el texto de la alerta
    time.sleep(5)
    alert = self.driver.switch_to.alert
    assert alert.text == "Datos reiniciados correctamente"
    alert.accept()
