# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebadeconcepto1Clientes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pruebadeconcepto1Clientes(self):
    self.driver.get("http://concasa-preventa.s3-website-us-east-1.amazonaws.com/login")
    self.driver.set_window_size(962, 1047)
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").send_keys("teresa.figueres@yopmail.com")
    self.driver.find_element(By.NAME, "passI").click()
    self.driver.find_element(By.NAME, "passI").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card").click()
    self.driver.find_element(By.NAME, "passI").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) > .initButtonLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Plan de compra").click()
    self.driver.get("http://concasa-real-estate.s3-website-us-east-1.amazonaws.com ")
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").send_keys("usiel.ramirez@concasa.com")
    self.driver.find_element(By.NAME, "passI").click()
    self.driver.find_element(By.NAME, "passI").send_keys("123456")
  
