# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebadeconcepto2Ventas():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pruebadeconcepto2Ventas(self):
    self.driver.get("http://concasa-real-estate.s3-website-us-east-1.amazonaws.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").send_keys("usiel.ramirez@concasa.com")
    self.driver.find_element(By.NAME, "passI").click()
    self.driver.find_element(By.NAME, "passI").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".section-container:nth-child(6) > .mr-2").click()
    self.driver.find_element(By.LINK_TEXT, "Gestión de ventas").click()
    self.driver.execute_script("window.scrollTo(0,600)")
    element = self.driver.find_element(By.LINK_TEXT, "2")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(1) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".info-section:nth-child(2) .amount-input").send_keys("20000")
    self.driver.find_element(By.CSS_SELECTOR, ".info-section:nth-child(2) .amount-input").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".create-plan-button")))
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
  
