# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestCrearPlanDePago():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window() #Pone el navegador en tamaño completo
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crear_plan_de_pago(self):

    #Inicio de sesión
    self.driver.get("http://concasa-real-estate.s3-website-us-east-1.amazonaws.com/")
    self.driver.maximize_window()
    self.driver.find_element(By.NAME, "emaiI").click()
    self.driver.find_element(By.NAME, "emaiI").send_keys("usiel.ramirez@concasa.com")
    self.driver.find_element(By.NAME, "passI").click()
    self.driver.find_element(By.NAME, "passI").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".section-container:nth-child(6) > .mr-2").click()

    # Redirección al apartado de gestión de ventas
    WebDriverWait(self.driver, 60).until(EC.visibility_of_element_located((By.LINK_TEXT, "Gestión de ventas")))
    WebDriverWait(self.driver, 60).until(EC.element_to_be_clickable((By.LINK_TEXT, "Gestión de ventas")))
    element = self.driver.find_element(By.LINK_TEXT, "Gestión de ventas")
    self.driver.execute_script("arguments[0].click();", element)



    #Selección del expediente que vamos a crearle un plan de pagos
    WebDriverWait(self.driver, 60).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".even:nth-child(1) > td:nth-child(1)"))) # el expediente que abrimos
    WebDriverWait(self.driver, 60).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".even:nth-child(1) > td:nth-child(1)")))
    element1 = self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(1) > td:nth-child(1)")
    self.driver.execute_script("arguments[0].click();", element1)


    #Creamos el plan de pago
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".create-plan-button")))
    element = self.driver.find_element(By.CSS_SELECTOR, ".create-plan-button")
    self.driver.execute_script("arguments[0].click();", element)
    WebDriverWait(self.driver, 60).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".swal2-confirm")))
    WebDriverWait(self.driver, 60).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".swal2-confirm")))
    element = self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm")
    self.driver.execute_script("arguments[0].click();", element)



