# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestTestaprobarplandepagocliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testaprobarplandepagocliente(self):
    # Test name: test_aprobar_plan_de_pago_cliente
    # Step # | name | target | value
    # 1 | open | http://concasa-preventa.s3-website-us-east-1.amazonaws.com/login | 
    self.driver.get("http://concasa-preventa.s3-website-us-east-1.amazonaws.com/login")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.maximize_window()
    # 3 | click | name=emaiI | 
    self.driver.find_element(By.NAME, "emaiI").click()
    # 4 | type | name=emaiI | prueba.cliente4.concasahome@yopmail.com
    self.driver.find_element(By.NAME, "emaiI").send_keys("prueba.cliente4.concasahome@yopmail.com")
    # 5 | click | name=passI | 
    self.driver.find_element(By.NAME, "passI").click()
    # 6 | type | name=passI | 123456
    self.driver.find_element(By.NAME, "passI").send_keys("123456")
    # 7 | sendKeys | name=passI | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "passI").send_keys(Keys.ENTER)
    # 8 | click | css=div:nth-child(10) > .initButtonLogin | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) > .initButtonLogin").click()
    # 9 | click | css=li:nth-child(2) .nav-text |
    WebDriverWait(self.driver, 60).until(EC.visibility_of_element_located((By.XPATH, "//li[2]/a/span")))
    WebDriverWait(self.driver, 60).until(EC.element_to_be_clickable((By.XPATH, "//li[2]/a/span")))
    self.driver.find_element(By.XPATH, "//li[2]/a/span").click()

    #Aprueba el plan de pagos
    #self.driver.find_element(By.XPATH, "//div[5]/button").click()
  
