name: Golive Dos X Semana

on: 
 schedule:
    - cron: '45 5 * * 1,4' # 11:45 pm Costa Rica time (UTC-6)


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-html
        pip install yagmail
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: List files
      run: ls -R

    - name: Run tests
      run: |
        pytest Golive/Produccion/Dos_X_Semana --html=reportprueba.html --self-contained-html

    - name: Verify report generation
      run: ls -l reportprueba.html

    - name: Send email with report
      if: always()
      run: |
        python send_email.py "Informe de pruebas automatizadas dos veces por semana"
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
