name: Golive Quincenal

on: 
 schedule:
    # Ejecutar todos los domingos del mes a las 11:35 PM hora de Costa Rica (UTC-6)
    - cron: '35 5 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-html
        pip install yagmail
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Verify day is first or third Sunday
      run: |
        DAY=$(date +'%d')
        if [[ $DAY -ge 1 && $DAY -le 7 ]]; then
          echo "First Sunday of the month"
        elif [[ $DAY -ge 15 && $DAY -le 21 ]]; then
          echo "Third Sunday of the month"
        else
          echo "Not the first or third Sunday of the month"
          exit 1
        fi

    - name: List files
      run: ls -R

    - name: Run tests
      run: |
        pytest Golive/Produccion/Quincenal --html=reportprueba.html --self-contained-html

    - name: Verify report generation
      run: ls -l reportprueba.html

    - name: Send email with report
      if: always()
      run: |
        python send_email.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENT: ${{ secrets.RECIPIENT }}
