name: Golive Quincenal

on: 
 schedule:
    # Ejecutar el primer y tercer lunes del mes a las 11:35 PM hora de Costa Rica (UTC-6)
    - cron: '50 5 2-8 * 2' # Primer lunes del mes (equivalente a 05:35 AM UTC del primer martes)
    - cron: '50 5 16-23 * 2' # Tercer lunes del mes (equivalente a 05:35 AM UTC del tercer martes)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-html
        pip install yagmail
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Verify day is first or third Monday
      run: |
        DAY=$(date +'%d')
        if [[ $DAY -ge 2 && $DAY -le 8 ]]; then
          echo "First Monday of the month"
        elif [[ $DAY -ge 16 && $DAY -le 23 ]]; then
          echo "Third Monday of the month"
        else
          echo "Not the first or third Monday of the month"
          exit 1
        fi

    - name: List files
      run: ls -R

    - name: Run tests
      run: |
        pytest Golive/Produccion/Quincenal --html=reportprueba.html --self-contained-html

    - name: Verify report generation
      run: ls -l reportprueba.html

    - name: Send email with report
      if: always()
      run: |
        python send_email.py "Informe de pruebas automatizadas quincenales"
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
